version: '3.8'
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    user: "0"
    depends_on:
      - tempo
    volumes:
      - ./config.yaml:/etc/otelcol-contrib/config.yaml
    networks:
      - observability
    ports:
      - "4317:4317"
      - "4318:4318"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3003:3000"
    volumes:
      - ./applications/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/tempo.yaml
    networks:
      - observability
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./applications/tempo/tempo.yaml:/etc/tempo.yaml
    networks:
      - observability
networks:
  observability:
    name: observability